name:  Build & Package Lambda

on:
  push:
    paths:
      - "app-src-code/**"
    branches:
      - main


env:
  AWS_REGION: us-west-2
  APP_TAG: ${{ github.sha }}
  APP_NAME: DotNetLambdaHelloWorld
  WORK_DIR: app-src-code/DotNetLambdaHelloWorld/src
  S3_BUCKET_NAME: dotnet-lambda-deployment-bucket

jobs:
  build-packaging:
    name: Build and Package Application
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: |
          cd ${{ env.WORK_DIR }}/DotNetLambdaHelloWorld
          dotnet restore

      - name: Install AWS Lambda Tools
        run: |
          cd ${{ env.WORK_DIR }}
          dotnet tool install -g Amazon.Lambda.Tools

      - name: Package Lambda function
        id: packaging
        run: |
          cd ${{ env.WORK_DIR }}
          dotnet lambda package --project-location  ${{ env.APP_NAME }} --output-package  ${{ env.APP_NAME }}-${{ env.APP_TAG }}.zip


      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

      - name: Upload Artifact to S3 
        run: |
           aws s3 cp ${{ env.WORK_DIR }}/${{ env.APP_NAME }}-${{ env.APP_TAG }}.zip s3://${{ env.S3_BUCKET_NAME }}/

