name: Lambda Deploy

on:
  workflow_run:
    workflows: ["Build & Package Lambda"]
    types:
      - completed
    branches:
      - "main"

env:
  AWS_REGION: us-west-2
  APP_TAG: ${{ github.sha }}
  APP_NAME: DotNetLambdaHelloWorld
  WORK_DIR: terraform-infra

jobs:
  deploy:
    name: Deploy DotNetLambdaHelloWorld Lambda to Dev Environment
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request'}}
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Initialize Terraform
        run: |
          cd ${{ env.WORK_DIR }}
          terraform init

      - name: Apply Terraform
        run: |
          cd ${{ env.WORK_DIR }}
          terraform apply -var "s3_key=${{ env.APP_NAME }}-${{ env.APP_TAG }}.zip" -auto-approve
